### PR TITLE
Add TheAwesomeCoder05.json

### PR DESCRIPTION
**Pull request by TheAwesomeCoder05**
Please add my license page at https://theawesomecoder05.mit-license.org.

### CODE REVIEW

**Comment by TheAwesomeCoder05** [comment]
@Richienb Thanks for merging the PR on suck short notice. I just wanted to know, how long does it take for the webpage to get built and deployed?

**Comment by Richienb** [comment]
Not sure how often Heroku rebuilds - check the [deployment log](https://github.com/remy/mit-license/deployments).

**Comment by TheAwesomeCoder05** [comment]
Sorry, but the deployment log gives and HTTP 404 error - The Page is Not Found.

**Comment by Richienb** [comment]
Here's a screenshot of the page:

Deployments

**Comment by TheAwesomeCoder05** [comment]
Thanks a lot!

**Comment by TheAwesomeCoder05** [comment]
Sorry for bothering again but I just visited the website and Heroku shows this error message:

image

**Comment by Richienb** [comment]
https://github.com/remy/mit-license/issues/1451

**Comment by TheAwesomeCoder05** [comment]
Yeah, it is some bug...

**Pull request merged**
