### PR TITLE
Migrate to Node + Improvements

### LINKED ISSUE #73: HTTP status codes in the API
In the API we create user files, I think API should also return HTTP codes like 200 OK, 403 forbidden etc.

I was gonna add this and send a PR but I'm not sure which HTTP status codes to return.

Any ideas?

### LINKED ISSUE #659: Multiple license-holders?
I've got a forked project. Tehcnically I can't say that the sole licensor of the project is the original creator, as several people have made large contributions. Any chance of allowing an array to be passed, instead of just a single licensor?

### LINKED ISSUE #765: ISC anyone?
Hi All,

Since it appears that the ISC license is starting to get pushed as a replacement for the MIT, would you ever consider adding the ISC to this project, or allowing a fork of it?

I'm not sure that it would be called, but thelicense.org, and thelicen.se are both available.

Thoughts?

### LINKED ISSUE #1286: Gravatar needs an alt attribute
According to Google Lighthouse, the gravatar image needs an alt attribute which should be easily added via the `name` key in the JSON file.

### LINKED ISSUE #1299: When will the API be re enabled
The MIT license API has been disabled for over a year. When will the API be reenabled?

### PR DESCRIPTION
**Pull request by Richienb**
This PR migrates `mit-license` to using Node, fixes the API and implements known good suggestions.

- [x] Migrate to Node
- [x] ALT attribute for Gravatar (Closes #1286)
- [x] Fix API (Closes #1299)
- [x] Support ISC (Closes #765)
- [x] Multiple copyright holders (Closes #659)
- [x] HTTP status codes for the API (Closes #73)
- [x] Auto minify files
- [x] Auto prefix css files
- [x] Improve tests

### CODE REVIEW

**Comment by Richienb** [comment]
It turns out that version pinning adds a whole host of boilerplate code that comes with it. Fortunately, it looks like none of the user files specifies a version meaning now might be a good time to deprecate it.

**Comment by Richienb** [comment]
The previous commit added some extra licenses as in the rewrite, you just need to add the license file itself to a folder for it to gain functionality.

**Comment by remy** [comment]
Quick couple of notes (I've not gone through the PR in much detail - only skimmed).

- github is saying there's 2,000+ files changed - you've not edited/saved the user json files have you? I'm not sure they should be modified as part of this PR (it add noise to your work)
- I think you've added different license types, but this isn't something I think makes sense for this project - mostly because the domain and project is mit-license.org - and I tend to lean towards simpler.

**Comment by Richienb** [comment]
> github is saying there's 2,000+ files changed - you've not edited/saved the user json files have you? I'm not sure they should be modified as part of this PR (it add noise to your work)
In https://github.com/remy/mit-license/pull/1348/commits/85180853dce4504dc2d7831d8fdd2c60ab791534 I formatted the user files so now all of them follow regular formatting.

> I think you've added different license types, but this isn't something I think makes sense for this project - mostly because the domain and project is mit-license.org - and I tend to lean towards simpler.
I understand. I'll just keep MIT and ISC then.

**Comment by Richienb** [comment]
@remy I'm pretty sure everything is done now. Over the next couple of days, I'll just test everything.

**Comment by Richienb** [comment]
@remy This PR is now complete. I've finished testing all the features and they appear working.

**IMPORTANT**: Set the `github_token` environmental variable in Heroku before merging this PR for the API to work in production.

If you'd like me to continue maintaining the code in the future, feel free to make me a collaborator on this repo.

Thank you.

**Comment by Richienb** [comment]
@remy The PR is complete. https://github.com/remy/mit-license/pull/1348#issuecomment-498003057

**Comment by remy** [comment]
If I've got time this weekend I'll make a start on review (if not, it'll be early next week - got camping with the kids' school)

**Comment by remy** [comment]
I'll start my review this or next week. It's possible I'm cherry pick parts in (to avoid doing a massive 2000+ file merge).

**Comment by remy** [comment]
Closing in favour of #1355.

Should be good to merge, but might be good to get another set of eyes on it.

**Pull request closed without merging**
