### PR TITLE
Add tryhtml Theme

### PR DESCRIPTION
**Pull request by abranhe**
Visit Live demo [here](https://tryht.ml/mit-license/LICENSE.html).

### CODE REVIEW

**Comment by Richienb** [comment]
Once #1355 is merged, we'll remove the browser prefixes and merge this PR.

**Comment by remy** [comment]
All themes must include a working demo and must be added to the README file.

The demo URL in this commit doesn't work - which is also why I prefer that it's hosted in JS Bin (as it's a project that I run and I know it'll remain live forevermore).

**Comment by Richienb** [comment]
> All themes must include a working demo and must be added to the README file.
> 
> The demo URL in this commit doesn't work - which is also why I prefer that it's hosted in JS Bin (as it's a project that I run and I know it'll remain live forevermore).

Got it. I'll update the files in a few minutes.

**Comment by Richienb** [comment]
Done.

**Pull request merged**
