### PR TITLE
Update jibreil.json

### PR DESCRIPTION
**Pull request by jibreil**
Sorry about this but the gravatar was showing the default one so I thought best to remove it all together, thanks! 👍

### CODE REVIEW

**Comment by squanto** [comment]
Hi @jibreil , your email currently shows as `"jibreilhoneine@gmail.com.com"`. Is that correct?

**Comment by jibreil** [comment]
No, there's an extra '.com', seems I accidentally put it there, sorry about that, could you fix it?

**Comment by jibreil** [comment]
That's correct @squanto could you accept this PR?

**Comment by squanto** [comment]
whoops 💯

**Comment by jibreil** [comment]
Thanks, :+1:

**Pull request merged**
