### PR TITLE
Patch shivapoudel and axisthemes

### PR DESCRIPTION
**Pull request by shivapoudel**

### CODE REVIEW

**Comment by shivapoudel** [comment]
@remy could you kindly merge this :)

**Comment by shivapoudel** [comment]
When will this changes be live :)

**Comment by remy** [comment]
It went live 5 days ago...

**Comment by shivapoudel** [comment]
Yeh, I know this PR gets merged 5 days ago....
I was not able to figure out why the theme has not changed as of this `axisthemes.json` file.

**Comment by remy** [comment]
Sorry, I don't tend to look to closely to the contents of the PRs. I checked the url and the license page came back. I'll take a look at what's online to see why its not changed in live.

**Comment by shivapoudel** [comment]
Also for `shivapoudel.json` ;)

**Comment by teppeis** [comment]
@remy @shivapoudel This repo has not worked since last year. https://github.com/remy/mit-license/issues/632

**Comment by shivapoudel** [comment]
@remy can you remove the `axisthemes.mit-license.org` and `shivapoudel.mit-license.org` so I can do that by using the API :P

**Pull request merged**
