### PR TITLE
Added: fremy; Thanks @rem for this nice initiative!

### PR DESCRIPTION
**Pull request by FremyCompany**
I ♥ it

### CODE REVIEW

**Comment by remy** [comment]
Urm, I'm not sure why, but it says the JSON is invalid...

**Comment by FremyCompany** [comment]
Uh, that's weird. Isn't that because your checker doesn't like the UTF8-BOM? Should I remove it?

**Comment by remy** [comment]
Possibly... if you can, please do remove it and see what grandmastertravis says.

**Comment by FremyCompany** [comment]
That was it. Text encoding ftw.

**Pull request merged**
