### PR TITLE
Major

### PR DESCRIPTION
**Pull request by LPLGong**
#### Before you create your license page

Hosting costs $7 a month. I need help, so please donate a few months to keep this service going.

I've already had support to run the domain until 2032, but the hosting needs help too.

**[Please donate and keep this project running](https://www.paypal.me/rem)**

### CODE REVIEW

**Comment by Richienb** [comment]
What is the purpose of this PR?

**Comment by remy** [comment]
Exactly what @Richienb said. This looks like maybe it was intended for an internal branch to @LPLGong - but at the very least, nuking the README ain't going to fly 😆

**Comment by Richienb** [comment]
@LPLGong Welcome to Github! What you just did was create a pull request to merge code at https://github.com/LPLGong/mit-license into the source, https://github.com/remy/mit-license. I'll close this out for now. For more information, see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests and if you would like to create your own MIT license page, see https://github.com/remy/mit-license#requesting-your-own-mit-license-page.

**Comment by Richienb** [comment]
On second look, this is probably just adding the CC-BY 4.0 license but with a bunch of unrelated changes.

**Pull request closed without merging**
