### PR TITLE
praveen Pal

### PR DESCRIPTION
**Pull request by PraveenPal4232**
#### Before you create your license page

Hosting costs $7 a month. I need help, so please donate a few months to keep this service going.

I've already had support to run the domain until 2032, but the hosting needs help too.

**[Please donate and keep this project running](https://www.paypal.me/rem)**

### CODE REVIEW

**Comment by PraveenPal4232** [comment]
Praveen Pal

**Comment by PraveenPal4232** [comment]
[LICENSE.txt](https://github.com/remy/mit-license/files/2647427/LICENSE.txt)

**Comment by PraveenPal4232** [comment]
Praveen Pal
[LICENSE.txt](https://github.com/remy/mit-license/files/2647431/LICENSE.txt)

**Comment by squanto** [comment]
Hey @PraveenPal4232 , why do you delete `$abas.json` and `1000ch.json`?

Also, why create both `4232praveenpal.json` and `praveenpal4232.json` as opposed to just one entry?

**Comment by PraveenPal4232** [comment]
Oops!  Sorry dude I will solve it soon as soon possible...(@-@)

**Comment by Richienb** [comment]
@PraveenPal4232 Your PR has been "merged" in https://github.com/remy/mit-license/commit/f9dc0860ee260e5c25fdea782f56fe4a7d7ef9e0

**Pull request closed without merging**
