### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Riz-waan**
Removed broken link from 8-bits theme.

### CODE REVIEW

**Comment by squanto** [comment]
Good catch. But rather than leave 8bit without a preview, could you replace the broken link with a link to a [working 8bit example](https://github.com/remy/mit-license/search?q=8bits&unscoped_q=8bits)?

**Comment by Riz-waan** [comment]
@squanto Check. I have added a working one to it.

**Comment by squanto** [comment]
Thanks @Riz-waan

**Comment by matricali** [comment]
I've created a new pull request fixing this issue.

This error was generated because I've changed my own Github username from `jorge-matricali` to `matricali` and `github.io` doesn't apply redirection to the new URL.
Sorry about that! :innocent:

**Pull request merged**
