### PR TITLE
Delete LICENSE

### PR DESCRIPTION
**Pull request by jeepdude1980**
#### Before you create your license page

Hosting costs $7 a month. I need help, so please donate a few months to keep this service going.

I've already had support to run the domain until 2032, but the hosting needs help too.

**[Please donate and keep this project running](https://www.paypal.me/rem)**

### CODE REVIEW

**Comment by remy** [comment]
Um…why?

**Comment by jeepdude1980** [comment]
Someone has hacked my accounts and they are using my information and I'm
sure you don't wanna be involved in it

**Comment by jeepdude1980** [comment]
Someone Has hacked my account and if you don't wanna be part of the lawsuit I think you should back off from whatever this is

**Comment by Richienb** [comment]
@jeepdude1980 Removing the license is probably not a good idea since that would modify the licensing rights, possible leading to actual lawsuits.

What the username of your hacked account? If you still have access to it, I highly recommend changing the password and enabling 2FA.

**Comment by ryahpalma** [comment]
This user is attempting to remove all Linux kernel licenses.

**Comment by Richienb** [comment]
@ryahpalma Thanks for that information.

**Pull request closed without merging**
