### PR TITLE
[Default theme] Minor CSS bugfixes

### PR DESCRIPTION
**Pull request by Ftornik**
Removed border on gravatar image

Fixed minor css issues based on csslint.com:
- Disallow units for 0 values (footer {  margin: 0em auto 2em auto;)
  – Heading (h1) has already been defined
  – margin-top can't be used with display inline (h1)

Code format based on Idiomatic CSS https://github.com/necolas/idiomatic-css

### CODE REVIEW

**Comment by remy** [comment]
Can you could include an update to the readme example of the theme too?

**Comment by Ftornik** [comment]
@remy Where is readme example located?

**Comment by remy** [comment]
https://github.com/remy/mit-license/blob/master/README.md#themes

**Comment by Ftornik** [comment]
Readme is updated now

**Comment by remy** [comment]
Ha, I meant the demo of the theme to make sure it was still the same, but yeah - and your name too :)

**Comment by benniemosher** [comment]
@remy Can we merge this PR in? @Ftornik has made the requested updates and the PR is passing CI. I would merge it in but I do not have the rights to do that yet (I will earn those though!). I personally :+1: this PR.

**Comment by remy** [comment]
No, he didn't. The readme doesn't have the preview link as all other themes do.

**Comment by benniemosher** [comment]
@remy Are you referring to the jsbin link that the other themes have linked to them?

**Pull request closed without merging**
