### PR TITLE
Add user: toolbear

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by toolbear** [comment]
Any luck, @remy? My license is still the default boilerplate.

**Comment by toolbear** [comment]
Should I try generating it with `curl`? I haven't done that because I was worried it'd just cause a conflict and make matters worse.

**Comment by rem** [comment]
Yeah, maybe give it a go. Worst case is it'll prevent the request.

**Comment by toolbear** [comment]
`curl` did the trick. Thanks again.

**Pull request merged**
